### ISSUE TITLE
"GET /download" downloaded a corrupted zip file that I can't open/unzip it

### ISSUE THREAD

**Issue by mmono** [gotwarlost/istanbul-middleware#18]

**Comment by mmono** [comment]
Here is the error when try to download the zip:

TypeError: Cannot set property 'covered' of undefined
    at /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:175:66
    at Array.forEach (native)
    at annotateLines (/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:173:28)
    at HtmlReport.Report.mix.writeDetailPage (/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:390:9)
    at /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:456:26
    at Object.ZipWriter.writeFile (/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/lib/zip-writer.js:62:9)
    at /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:455:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:449:23)
    at /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mantis/istanbul/node_modules/istanbul-middleware/node_modules/istanbul/lib/report/html.js:451:22

**Comment by epoberezkin** [comment]
I also have a .zip file that I can't unzip so far but there is no error in the server.
The default Archive utility of Mac OS X shows this error: "Unable to expand "coverage.zip" into Downloads (Error 2 - No such file or directory)"

**Comment by epoberezkin** [comment]
The workaround is to use the undocumented `/object` endpoint

**Comment by jmgamboa** [comment]
@epoberezkin did you recall what you did? having the same issue
