### ISSUE TITLE
Selenium Istanbul-Middleware Istanbul-Instrumenter-Loader Issue: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gowritharanmageswarasc** [gotwarlost/istanbul-middleware#41]
Overview:

I am trying to retrieve code coverage data after selenium tests have run.  I seem to be close but at the last step issue I cannot seem to figure out.  Here are my steps to doing this:

1. Instrument the JS source code using istanbul-instrumenter-loader as a post step in webpack-dev-server and deliver it to the browser (the last step of webpack config file):

```
      // instrument only testing sources with Istanbul
      {
          test: /\.js$|\.jsx$/,
          exclude: /node_modules|test|webpack/,
          enforce: 'post',
          //include: path.resolve('src/components/'),
          loader: 'istanbul-instrumenter-loader',
          query: {
              esModules: true
          }
      },
```

2. Setup an express/istanbul-middleware server to post/retrieve code coverage data

```
var coverage = require('istanbul-middleware');
var express = require('express');
var app = express();

app.use('/coverage', coverage.createHandler());
app.listen(8089);
```

3. Add code to the end of your selenium test to post the code coverage data

```
      // post coverage info
      browser.frameParent();
      var coverageData = browser.execute("return window.__coverage__;");

      var covStr = JSON.stringify(coverageData);
      console.log(covStr);
      var http = require('http');
      var post_options = {
          port: 8089,
          host: 'localhost',
          path: '/coverage/client',
          method: 'POST',
          headers: {
              'Content-Type': 'application/json',
          }
      };

      // Set up the request
      var post_req = http.request(post_options, function(res) {
          console.log('STATUS: ' + res.statusCode);
          console.log('HEADERS: ' + JSON.stringify(res.headers));
          res.setEncoding('utf8');
          res.on('data', function (chunk) {
              console.log('Response FROM COVERAGE SERVER: ' + chunk);
          });
      });

      post_req.on('error', function(e) {
          console.log('problem with request: ' + e.message);
      });

      post_req.write(covStr);
      post_req.end();
```

At this step I am able to get code coverage data back from the browser and post it to the server which returns:

```
STATUS: 200
HEADERS: {"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"11","etag":"W/\"b-Ai2R8hgEarLmHKwesT1qcY913ys\"","date":"Sat, 15 Apr 2017 00:53:21 GMT","connection":"close"}
Response FROM COVERAGE SERVER: {"ok":true}
```

4.  When I go to http://localhost:8089/coverage/ or http://localhost:8089/coverage/download to see the reports I get this error:

> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at Object.addDerivedInfoForFile (/Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul/lib/object-utils.js:58:20)
>     at Collector.fileCoverageFor (/Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul/lib/collector.js:94:15)
>     at /Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul/lib/report/html.js:558:90
>     at Array.forEach (native)
>     at HtmlReport.writeReport (/Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul/lib/report/html.js:557:27)
>     at /Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul-middleware/lib/handlers.js:112:20
>     at Array.forEach (native)
>     at /Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/istanbul-middleware/lib/handlers.js:111:17
>     at Layer.handle [as handle_request] (/Users/gowritharan.mageswara/geofilters-on-demand/web/client/node_modules/express/lib/router/layer.js:95:5)

Can anyone help me with this issue?  I am guessing it is my data but is there a way to verify my data is not improper? Or download the raw data that is posted to the express server? Thank you in advance!

**Comment by gowritharanmageswarasc** [comment]
Closing this.  The issue was that `windows.__coverage__` was returning extra JSON data that the middleware could not interpret.  The fix was to only send the data the middleware expects in your selenium tests:

```
let coverageStr = browser.execute("return window.__coverage__;");
let covJSON = JSON.stringify(coverageStr['value']);
```
